# Generated by Django 3.2.12 on 2022-03-06 12:18

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year_production',
            field=models.PositiveIntegerField(default=2022, validators=[api_app.models.max_value_current_year]),
        ),
    ]
